#!/bin/bash

rootfs_9p="$PWD/rootfs/"
kvm_image="$PWD/app-elfloader_kvm-x86_64"
bridge_iface="uk0"
bridge_ip="172.44.0.1"
vm_ip="172.44.0.2"
netmask="255.255.255.0"
netmask_prefix="24"
net_args="netdev.ipv4_addr=$vm_ip netdev.ipv4_gw_addr=$bridge_ip netdev.ipv4_subnet_mask=$netmask"
net_up_script="$PWD/setup/up"
net_down_script="$PWD/setup/down"
