#!/bin/bash

kvm_image="$PWD/app-elfloader_kvm-x86_64"
bridge_iface="uk0"
bridge_ip="172.44.0.1"
vm_ip="172.44.0.2"
netmask="255.255.255.0"
netmask_prefix="24"
net_args="netdev.ipv4_addr=$vm_ip netdev.ipv4_gw_addr=$bridge_ip netdev.ipv4_subnet_mask=$netmask"
net_up_script="$PWD/setup/up"
net_down_script="$PWD/setup/down"

if test "$#" -ne 1; then
    echo "Usage: $0 path/to/exec" 1>&2
    exit 1
fi

exec_to_load="$1"

# Configure bridge interface.
echo "Creating bridge $bridge_iface if it does not exist ..."
ip -d link show "$bridge_iface" 2> /dev/null | tail -1 | grep bridge > /dev/null 2>&1
if test $? -ne 0; then
    sudo ip address flush dev "$bridge_iface" > /dev/null 2>&1
    sudo ip link del dev "$bridge_iface" > /dev/null 2>&1
    sudo ip link add "$bridge_iface" type bridge > /dev/null 2>&1
fi

echo "Adding IP address $bridge_ip to bridge $bridge_iface ..."
sudo ip address flush dev "$bridge_iface"
sudo ip address add "$bridge_ip"/"$netmask_prefix" dev "$bridge_iface"
sudo ip link set dev "$bridge_iface" up

# Create setup folder if it doesn't exist.
if test ! -d "$PWD/setup"; then
    rm -fr "$PWD/setup"
    mkdir "$PWD/setup"
fi

# Configure network setup scripts.
cat > "$net_up_script" <<END
#!/bin/bash

sudo ip link set dev "\$1" up
sudo ip link set dev "\$1" master "$bridge_iface"
END

cat > "$net_down_script" <<END
#!/bin/bash

sudo ip link set dev "\$1" nomaster
sudo ip link set dev "\$1" down
END

chmod a+x setup/up
chmod a+x setup/down


# Start QEMU VM.
sudo qemu-system-x86_64 \
    -m 2G -enable-kvm -nographic -nodefaults \
    -display none -serial stdio -device isa-debug-exit \
    -kernel "$kvm_image" \
    -netdev tap,id=hnet0,vhost=off,script="$net_up_script",downscript="$net_down_script" -device virtio-net-pci,netdev=hnet0,id=net0 \
    -initrd "$exec_to_load" \
    -append "$net_args -- hello $exec_to_load"
